/**
 * Hooks setup module.
 *
 * Installs the state-reporter script to ~/.claude-deck/hooks/ and
 * merges hook configuration into ~/.claude/settings.json idempotently.
 */

import * as fs from "fs";
import * as path from "path";
import * as os from "os";

const CLAUDE_DECK_DIR = path.join(os.homedir(), ".claude-deck");
const HOOKS_DIR = path.join(CLAUDE_DECK_DIR, "hooks");
const STATES_DIR = path.join(CLAUDE_DECK_DIR, "session-states");
const REPORTER_PATH = path.join(HOOKS_DIR, "state-reporter");
const SETTINGS_PATH = path.join(os.homedir(), ".claude", "settings.json");

// Events we hook into and whether they run async
const HOOK_EVENTS: Array<{ event: string; async: boolean }> = [
  { event: "UserPromptSubmit", async: true },
  { event: "PreToolUse", async: true },
  { event: "PermissionRequest", async: false }, // sync so state file exists before dialog
  { event: "Stop", async: true },
  { event: "SessionStart", async: true },
  { event: "SessionEnd", async: true },
];

function installReporterScript(): void {
  fs.mkdirSync(HOOKS_DIR, { recursive: true });
  fs.mkdirSync(STATES_DIR, { recursive: true });

  // Write a shell wrapper that invokes the reporter via tsx/node
  // The reporter.ts is compiled into the project, so we use node with tsx
  const projectRoot = path.resolve(__dirname, "../..");
  const reporterSource = path.join(projectRoot, "lib/hooks/reporter.ts");

  const script = [
    "#!/bin/bash",
    "# Auto-generated by claude-deck. Do not edit.",
    `exec tsx "${reporterSource}" 2>/dev/null || exec npx tsx "${reporterSource}" 2>/dev/null`,
  ].join("\n");

  fs.writeFileSync(REPORTER_PATH, script, { mode: 0o755 });
}

interface HookCommand {
  type: "command";
  command: string;
  async?: boolean;
}

interface HookMatcher {
  matcher?: string;
  hooks: HookCommand[];
}

type SettingsHooks = Record<string, HookMatcher[]>;

interface Settings {
  hooks?: SettingsHooks;
  [key: string]: unknown;
}

function isOurHook(hook: HookCommand): boolean {
  return hook.command === REPORTER_PATH;
}

function mergeHooksIntoSettings(): void {
  let settings: Settings = {};

  try {
    const raw = fs.readFileSync(SETTINGS_PATH, "utf-8");
    settings = JSON.parse(raw);
  } catch {
    // File doesn't exist or is invalid — start fresh
  }

  if (!settings.hooks) {
    settings.hooks = {};
  }

  let changed = false;

  for (const { event, async: isAsync } of HOOK_EVENTS) {
    if (!settings.hooks[event]) {
      settings.hooks[event] = [];
    }

    const eventHooks = settings.hooks[event];

    // Check if we already have our hook installed
    const alreadyInstalled = eventHooks.some((matcher) =>
      matcher.hooks?.some((h) => isOurHook(h))
    );

    if (!alreadyInstalled) {
      const hookDef: HookCommand = {
        type: "command",
        command: REPORTER_PATH,
      };
      if (isAsync) {
        hookDef.async = true;
      }

      eventHooks.push({ hooks: [hookDef] });
      changed = true;
    }
  }

  if (changed) {
    // Ensure ~/.claude directory exists
    fs.mkdirSync(path.dirname(SETTINGS_PATH), { recursive: true });
    fs.writeFileSync(SETTINGS_PATH, JSON.stringify(settings, null, 2) + "\n");
    console.log("> Hooks configured in ~/.claude/settings.json");
  }
}

export function setupHooks(): void {
  try {
    installReporterScript();
    mergeHooksIntoSettings();
    console.log(
      "> Hook reporter installed at ~/.claude-deck/hooks/state-reporter"
    );
  } catch (err) {
    console.error("Failed to setup hooks:", err);
  }
}

export { STATES_DIR };
